// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sagenft/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryListNftItemRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListNftItemRequest) Reset()         { *m = QueryListNftItemRequest{} }
func (m *QueryListNftItemRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListNftItemRequest) ProtoMessage()    {}
func (*QueryListNftItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{2}
}
func (m *QueryListNftItemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListNftItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListNftItemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListNftItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListNftItemRequest.Merge(m, src)
}
func (m *QueryListNftItemRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListNftItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListNftItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListNftItemRequest proto.InternalMessageInfo

func (m *QueryListNftItemRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListNftItemResponse struct {
	NftItem    []*NftItem          `protobuf:"bytes,1,rep,name=NftItem,proto3" json:"NftItem,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListNftItemResponse) Reset()         { *m = QueryListNftItemResponse{} }
func (m *QueryListNftItemResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListNftItemResponse) ProtoMessage()    {}
func (*QueryListNftItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{3}
}
func (m *QueryListNftItemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListNftItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListNftItemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListNftItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListNftItemResponse.Merge(m, src)
}
func (m *QueryListNftItemResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListNftItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListNftItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListNftItemResponse proto.InternalMessageInfo

func (m *QueryListNftItemResponse) GetNftItem() []*NftItem {
	if m != nil {
		return m.NftItem
	}
	return nil
}

func (m *QueryListNftItemResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryShowNftItemRequest struct {
	NftId uint64 `protobuf:"varint,1,opt,name=nftId,proto3" json:"nftId,omitempty"`
}

func (m *QueryShowNftItemRequest) Reset()         { *m = QueryShowNftItemRequest{} }
func (m *QueryShowNftItemRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowNftItemRequest) ProtoMessage()    {}
func (*QueryShowNftItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{4}
}
func (m *QueryShowNftItemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowNftItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowNftItemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowNftItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowNftItemRequest.Merge(m, src)
}
func (m *QueryShowNftItemRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowNftItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowNftItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowNftItemRequest proto.InternalMessageInfo

func (m *QueryShowNftItemRequest) GetNftId() uint64 {
	if m != nil {
		return m.NftId
	}
	return 0
}

type QueryShowNftItemResponse struct {
	NftItem *NftItem `protobuf:"bytes,1,opt,name=NftItem,proto3" json:"NftItem,omitempty"`
}

func (m *QueryShowNftItemResponse) Reset()         { *m = QueryShowNftItemResponse{} }
func (m *QueryShowNftItemResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowNftItemResponse) ProtoMessage()    {}
func (*QueryShowNftItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{5}
}
func (m *QueryShowNftItemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowNftItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowNftItemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowNftItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowNftItemResponse.Merge(m, src)
}
func (m *QueryShowNftItemResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowNftItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowNftItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowNftItemResponse proto.InternalMessageInfo

func (m *QueryShowNftItemResponse) GetNftItem() *NftItem {
	if m != nil {
		return m.NftItem
	}
	return nil
}

type QueryListNftIdOfOwnerRequest struct {
	OwnerAddress string             `protobuf:"bytes,1,opt,name=ownerAddress,proto3" json:"ownerAddress,omitempty"`
	Pagination   *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListNftIdOfOwnerRequest) Reset()         { *m = QueryListNftIdOfOwnerRequest{} }
func (m *QueryListNftIdOfOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListNftIdOfOwnerRequest) ProtoMessage()    {}
func (*QueryListNftIdOfOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{6}
}
func (m *QueryListNftIdOfOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListNftIdOfOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListNftIdOfOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListNftIdOfOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListNftIdOfOwnerRequest.Merge(m, src)
}
func (m *QueryListNftIdOfOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListNftIdOfOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListNftIdOfOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListNftIdOfOwnerRequest proto.InternalMessageInfo

func (m *QueryListNftIdOfOwnerRequest) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *QueryListNftIdOfOwnerRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListNftIdOfOwnerResponse struct {
	NftIdList  []uint64            `protobuf:"varint,1,rep,packed,name=nftIdList,proto3" json:"nftIdList,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListNftIdOfOwnerResponse) Reset()         { *m = QueryListNftIdOfOwnerResponse{} }
func (m *QueryListNftIdOfOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListNftIdOfOwnerResponse) ProtoMessage()    {}
func (*QueryListNftIdOfOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{7}
}
func (m *QueryListNftIdOfOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListNftIdOfOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListNftIdOfOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListNftIdOfOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListNftIdOfOwnerResponse.Merge(m, src)
}
func (m *QueryListNftIdOfOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListNftIdOfOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListNftIdOfOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListNftIdOfOwnerResponse proto.InternalMessageInfo

func (m *QueryListNftIdOfOwnerResponse) GetNftIdList() []uint64 {
	if m != nil {
		return m.NftIdList
	}
	return nil
}

func (m *QueryListNftIdOfOwnerResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryNftCountOfRequest struct {
	OwnerAddress string `protobuf:"bytes,1,opt,name=ownerAddress,proto3" json:"ownerAddress,omitempty"`
}

func (m *QueryNftCountOfRequest) Reset()         { *m = QueryNftCountOfRequest{} }
func (m *QueryNftCountOfRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNftCountOfRequest) ProtoMessage()    {}
func (*QueryNftCountOfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{8}
}
func (m *QueryNftCountOfRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNftCountOfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNftCountOfRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNftCountOfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNftCountOfRequest.Merge(m, src)
}
func (m *QueryNftCountOfRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNftCountOfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNftCountOfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNftCountOfRequest proto.InternalMessageInfo

func (m *QueryNftCountOfRequest) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

type QueryNftCountOfResponse struct {
	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *QueryNftCountOfResponse) Reset()         { *m = QueryNftCountOfResponse{} }
func (m *QueryNftCountOfResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNftCountOfResponse) ProtoMessage()    {}
func (*QueryNftCountOfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d680890b7adebc71, []int{9}
}
func (m *QueryNftCountOfResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNftCountOfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNftCountOfResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNftCountOfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNftCountOfResponse.Merge(m, src)
}
func (m *QueryNftCountOfResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNftCountOfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNftCountOfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNftCountOfResponse proto.InternalMessageInfo

func (m *QueryNftCountOfResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "blog.sagenft.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "blog.sagenft.QueryParamsResponse")
	proto.RegisterType((*QueryListNftItemRequest)(nil), "blog.sagenft.QueryListNftItemRequest")
	proto.RegisterType((*QueryListNftItemResponse)(nil), "blog.sagenft.QueryListNftItemResponse")
	proto.RegisterType((*QueryShowNftItemRequest)(nil), "blog.sagenft.QueryShowNftItemRequest")
	proto.RegisterType((*QueryShowNftItemResponse)(nil), "blog.sagenft.QueryShowNftItemResponse")
	proto.RegisterType((*QueryListNftIdOfOwnerRequest)(nil), "blog.sagenft.QueryListNftIdOfOwnerRequest")
	proto.RegisterType((*QueryListNftIdOfOwnerResponse)(nil), "blog.sagenft.QueryListNftIdOfOwnerResponse")
	proto.RegisterType((*QueryNftCountOfRequest)(nil), "blog.sagenft.QueryNftCountOfRequest")
	proto.RegisterType((*QueryNftCountOfResponse)(nil), "blog.sagenft.QueryNftCountOfResponse")
}

func init() { proto.RegisterFile("sagenft/query.proto", fileDescriptor_d680890b7adebc71) }

var fileDescriptor_d680890b7adebc71 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x4f, 0x13, 0x41,
	0x14, 0xc7, 0x3b, 0x48, 0x31, 0x4c, 0x39, 0x98, 0x61, 0x45, 0xb2, 0x96, 0x15, 0x17, 0x41, 0x84,
	0x64, 0x27, 0x2d, 0x27, 0x13, 0x2f, 0x62, 0xa2, 0x21, 0x1a, 0xc0, 0xf5, 0xe6, 0xa5, 0x99, 0xd2,
	0xd9, 0x65, 0x63, 0xbb, 0xb3, 0x74, 0x06, 0x91, 0x10, 0x0e, 0x7a, 0x30, 0xd1, 0x78, 0x30, 0xd1,
	0xcf, 0xe0, 0xa7, 0xf0, 0x03, 0x70, 0x24, 0xf1, 0xe2, 0xc9, 0x18, 0xf0, 0x83, 0x98, 0x9d, 0x99,
	0xa5, 0x3b, 0xed, 0x42, 0xd5, 0x78, 0x63, 0xdf, 0xfc, 0xe7, 0xbd, 0xdf, 0x7f, 0xde, 0x7b, 0x14,
	0x4e, 0x72, 0x12, 0xd2, 0x38, 0x10, 0x78, 0x67, 0x97, 0x76, 0xf7, 0xbd, 0xa4, 0xcb, 0x04, 0x43,
	0x13, 0xcd, 0x36, 0x0b, 0x3d, 0x7d, 0x62, 0x5b, 0x21, 0x0b, 0x99, 0x3c, 0xc0, 0xe9, 0x5f, 0x4a,
	0x63, 0x57, 0x43, 0xc6, 0xc2, 0x36, 0xc5, 0x24, 0x89, 0x30, 0x89, 0x63, 0x26, 0x88, 0x88, 0x58,
	0xcc, 0xf5, 0xe9, 0xd2, 0x16, 0xe3, 0x1d, 0xc6, 0x71, 0x93, 0x70, 0xaa, 0x52, 0xe3, 0x97, 0xb5,
	0x26, 0x15, 0xa4, 0x86, 0x13, 0x12, 0x46, 0xb1, 0x14, 0x6b, 0xad, 0x95, 0x21, 0x24, 0xa4, 0x4b,
	0x3a, 0x59, 0x86, 0xa9, 0x2c, 0x1a, 0x07, 0xa2, 0x11, 0x09, 0xda, 0x51, 0x71, 0xd7, 0x82, 0xe8,
	0x69, 0x9a, 0x6f, 0x53, 0x8a, 0x7d, 0xba, 0xb3, 0x4b, 0xb9, 0x70, 0xd7, 0xe0, 0xa4, 0x11, 0xe5,
	0x09, 0x8b, 0x39, 0x45, 0x75, 0x38, 0xa6, 0x92, 0x4e, 0x83, 0x59, 0xb0, 0x58, 0xa9, 0x5b, 0x5e,
	0xde, 0x99, 0xa7, 0xd4, 0xab, 0xa3, 0x47, 0x3f, 0x6e, 0x94, 0x7c, 0xad, 0x74, 0x09, 0xbc, 0x26,
	0x53, 0x3d, 0x89, 0xb8, 0x58, 0x0f, 0xc4, 0x9a, 0xa0, 0x1d, 0x5d, 0x05, 0x3d, 0x84, 0xb0, 0x47,
	0xaf, 0x53, 0x2e, 0x78, 0xca, 0xaa, 0x97, 0x5a, 0xf5, 0xd4, 0x2b, 0x6a, 0xab, 0xde, 0x26, 0x09,
	0xa9, 0xbe, 0xeb, 0xe7, 0x6e, 0xba, 0x9f, 0x01, 0x9c, 0x1e, 0xac, 0xa1, 0x99, 0x31, 0xbc, 0xac,
	0x43, 0xd3, 0x60, 0xf6, 0xd2, 0x62, 0xa5, 0x7e, 0xd5, 0x84, 0xce, 0xf4, 0x99, 0x0a, 0x3d, 0x32,
	0xa8, 0x46, 0x24, 0xd5, 0xed, 0xa1, 0x54, 0xaa, 0x9a, 0x81, 0x85, 0xb5, 0xf3, 0x67, 0xdb, 0x6c,
	0xaf, 0xcf, 0xb9, 0x05, 0xcb, 0x71, 0x20, 0xd6, 0x5a, 0xd2, 0xf4, 0xa8, 0xaf, 0x3e, 0xdc, 0xc7,
	0xda, 0x86, 0x71, 0xa1, 0xc8, 0x06, 0x18, 0x6e, 0xc3, 0x7d, 0x0f, 0x60, 0xd5, 0x78, 0x94, 0xd6,
	0x46, 0xb0, 0xb1, 0x17, 0xd3, 0x6e, 0xc6, 0xe0, 0xc2, 0x09, 0x96, 0x7e, 0xdf, 0x6f, 0xb5, 0xba,
	0x94, 0xab, 0x96, 0x8e, 0xfb, 0x46, 0xac, 0xaf, 0x43, 0x23, 0xff, 0xdc, 0xa1, 0xb7, 0x00, 0xce,
	0x9c, 0x03, 0xa3, 0xfd, 0x55, 0xe1, 0xb8, 0x7c, 0x84, 0x54, 0x20, 0x1b, 0x35, 0xea, 0xf7, 0x02,
	0xff, 0xaf, 0x27, 0xf7, 0xe0, 0x94, 0xe4, 0x58, 0x0f, 0xc4, 0x03, 0xb6, 0x1b, 0x8b, 0x8d, 0xe0,
	0x2f, 0x9e, 0xe3, 0xac, 0xa3, 0xf9, 0xdb, 0x9a, 0xdf, 0x82, 0x65, 0xc1, 0x04, 0x69, 0x67, 0x1d,
	0x95, 0x1f, 0xf5, 0xaf, 0x65, 0x58, 0x96, 0x37, 0xd0, 0x0b, 0x38, 0xa6, 0xd6, 0x03, 0xcd, 0x9a,
	0x8d, 0x1b, 0xdc, 0x3e, 0xfb, 0xe6, 0x05, 0x0a, 0x55, 0xce, 0xad, 0xbe, 0xf9, 0xf6, 0xeb, 0xd3,
	0xc8, 0x14, 0xb2, 0x70, 0x2a, 0xc5, 0xe6, 0xca, 0xa3, 0xd7, 0x00, 0x56, 0x72, 0xbb, 0x80, 0xe6,
	0x0b, 0x12, 0x0e, 0xee, 0xa3, 0xbd, 0x30, 0x4c, 0xa6, 0x8b, 0xcf, 0xc9, 0xe2, 0x33, 0xe8, 0xba,
	0x59, 0xbc, 0x1d, 0x71, 0xd1, 0xc8, 0xfe, 0xbd, 0xa0, 0x77, 0x00, 0x56, 0x72, 0x83, 0x5c, 0xc8,
	0x30, 0xb8, 0x19, 0x85, 0x0c, 0x05, 0xfb, 0xe0, 0x2e, 0x4b, 0x86, 0x79, 0x34, 0x67, 0x32, 0xf0,
	0x6d, 0xb6, 0x77, 0xc6, 0x80, 0x0f, 0xe4, 0x04, 0x1d, 0xa2, 0x2f, 0x00, 0x5e, 0xe9, 0x9f, 0x3c,
	0xb4, 0x74, 0x81, 0xdb, 0xbe, 0x5d, 0xb1, 0x97, 0xff, 0x48, 0xab, 0xd1, 0xee, 0x4a, 0xb4, 0x15,
	0x54, 0x3b, 0xef, 0x79, 0x5a, 0x0d, 0x16, 0x34, 0xe4, 0x60, 0xe1, 0x83, 0xfc, 0x7c, 0x1d, 0xa2,
	0x0f, 0x00, 0xc2, 0xde, 0x70, 0xa1, 0x5b, 0x05, 0x65, 0x07, 0x26, 0xd7, 0x9e, 0x1f, 0xa2, 0xd2,
	0x58, 0x35, 0x89, 0xb5, 0x8c, 0xee, 0x98, 0x58, 0x29, 0xd1, 0x56, 0x2a, 0x6d, 0xb0, 0xa0, 0x0f,
	0x67, 0xd5, 0x3b, 0x3a, 0x71, 0xc0, 0xf1, 0x89, 0x03, 0x7e, 0x9e, 0x38, 0xe0, 0xe3, 0xa9, 0x53,
	0x3a, 0x3e, 0x75, 0x4a, 0xdf, 0x4f, 0x9d, 0xd2, 0x73, 0x4b, 0xe6, 0x78, 0x75, 0x96, 0x45, 0xec,
	0x27, 0x94, 0x37, 0xc7, 0xe4, 0x6f, 0xca, 0xca, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x5c,
	0xbb, 0x6b, 0x06, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ListNftItem items.
	ListNftItem(ctx context.Context, in *QueryListNftItemRequest, opts ...grpc.CallOption) (*QueryListNftItemResponse, error)
	// Queries a list of ShowNftItem items.
	ShowNftItem(ctx context.Context, in *QueryShowNftItemRequest, opts ...grpc.CallOption) (*QueryShowNftItemResponse, error)
	// Queries a list of ListNftIdOfOwner items.
	ListNftIdOfOwner(ctx context.Context, in *QueryListNftIdOfOwnerRequest, opts ...grpc.CallOption) (*QueryListNftIdOfOwnerResponse, error)
	// Queries a list of NftCountOf items.
	NftCountOf(ctx context.Context, in *QueryNftCountOfRequest, opts ...grpc.CallOption) (*QueryNftCountOfResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/blog.sagenft.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListNftItem(ctx context.Context, in *QueryListNftItemRequest, opts ...grpc.CallOption) (*QueryListNftItemResponse, error) {
	out := new(QueryListNftItemResponse)
	err := c.cc.Invoke(ctx, "/blog.sagenft.Query/ListNftItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowNftItem(ctx context.Context, in *QueryShowNftItemRequest, opts ...grpc.CallOption) (*QueryShowNftItemResponse, error) {
	out := new(QueryShowNftItemResponse)
	err := c.cc.Invoke(ctx, "/blog.sagenft.Query/ShowNftItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListNftIdOfOwner(ctx context.Context, in *QueryListNftIdOfOwnerRequest, opts ...grpc.CallOption) (*QueryListNftIdOfOwnerResponse, error) {
	out := new(QueryListNftIdOfOwnerResponse)
	err := c.cc.Invoke(ctx, "/blog.sagenft.Query/ListNftIdOfOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NftCountOf(ctx context.Context, in *QueryNftCountOfRequest, opts ...grpc.CallOption) (*QueryNftCountOfResponse, error) {
	out := new(QueryNftCountOfResponse)
	err := c.cc.Invoke(ctx, "/blog.sagenft.Query/NftCountOf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ListNftItem items.
	ListNftItem(context.Context, *QueryListNftItemRequest) (*QueryListNftItemResponse, error)
	// Queries a list of ShowNftItem items.
	ShowNftItem(context.Context, *QueryShowNftItemRequest) (*QueryShowNftItemResponse, error)
	// Queries a list of ListNftIdOfOwner items.
	ListNftIdOfOwner(context.Context, *QueryListNftIdOfOwnerRequest) (*QueryListNftIdOfOwnerResponse, error)
	// Queries a list of NftCountOf items.
	NftCountOf(context.Context, *QueryNftCountOfRequest) (*QueryNftCountOfResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ListNftItem(ctx context.Context, req *QueryListNftItemRequest) (*QueryListNftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNftItem not implemented")
}
func (*UnimplementedQueryServer) ShowNftItem(ctx context.Context, req *QueryShowNftItemRequest) (*QueryShowNftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowNftItem not implemented")
}
func (*UnimplementedQueryServer) ListNftIdOfOwner(ctx context.Context, req *QueryListNftIdOfOwnerRequest) (*QueryListNftIdOfOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNftIdOfOwner not implemented")
}
func (*UnimplementedQueryServer) NftCountOf(ctx context.Context, req *QueryNftCountOfRequest) (*QueryNftCountOfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NftCountOf not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.sagenft.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListNftItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListNftItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListNftItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.sagenft.Query/ListNftItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListNftItem(ctx, req.(*QueryListNftItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowNftItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowNftItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowNftItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.sagenft.Query/ShowNftItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowNftItem(ctx, req.(*QueryShowNftItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListNftIdOfOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListNftIdOfOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListNftIdOfOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.sagenft.Query/ListNftIdOfOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListNftIdOfOwner(ctx, req.(*QueryListNftIdOfOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NftCountOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNftCountOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NftCountOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.sagenft.Query/NftCountOf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NftCountOf(ctx, req.(*QueryNftCountOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.sagenft.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ListNftItem",
			Handler:    _Query_ListNftItem_Handler,
		},
		{
			MethodName: "ShowNftItem",
			Handler:    _Query_ShowNftItem_Handler,
		},
		{
			MethodName: "ListNftIdOfOwner",
			Handler:    _Query_ListNftIdOfOwner_Handler,
		},
		{
			MethodName: "NftCountOf",
			Handler:    _Query_NftCountOf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sagenft/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListNftItemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListNftItemRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListNftItemRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListNftItemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListNftItemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListNftItemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NftItem) > 0 {
		for iNdEx := len(m.NftItem) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NftItem[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowNftItemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowNftItemRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowNftItemRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NftId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.NftId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowNftItemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowNftItemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowNftItemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NftItem != nil {
		{
			size, err := m.NftItem.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListNftIdOfOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListNftIdOfOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListNftIdOfOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListNftIdOfOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListNftIdOfOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListNftIdOfOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NftIdList) > 0 {
		dAtA8 := make([]byte, len(m.NftIdList)*10)
		var j7 int
		for _, num := range m.NftIdList {
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintQuery(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryNftCountOfRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNftCountOfRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNftCountOfRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryNftCountOfResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNftCountOfResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNftCountOfResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Total != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListNftItemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListNftItemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NftItem) > 0 {
		for _, e := range m.NftItem {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowNftItemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NftId != 0 {
		n += 1 + sovQuery(uint64(m.NftId))
	}
	return n
}

func (m *QueryShowNftItemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NftItem != nil {
		l = m.NftItem.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListNftIdOfOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListNftIdOfOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NftIdList) > 0 {
		l = 0
		for _, e := range m.NftIdList {
			l += sovQuery(uint64(e))
		}
		n += 1 + sovQuery(uint64(l)) + l
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryNftCountOfRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryNftCountOfResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Total != 0 {
		n += 1 + sovQuery(uint64(m.Total))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListNftItemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListNftItemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListNftItemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListNftItemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListNftItemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListNftItemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftItem = append(m.NftItem, &NftItem{})
			if err := m.NftItem[len(m.NftItem)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowNftItemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowNftItemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowNftItemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftId", wireType)
			}
			m.NftId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NftId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowNftItemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowNftItemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowNftItemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NftItem == nil {
				m.NftItem = &NftItem{}
			}
			if err := m.NftItem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListNftIdOfOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListNftIdOfOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListNftIdOfOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListNftIdOfOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListNftIdOfOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListNftIdOfOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.NftIdList = append(m.NftIdList, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthQuery
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthQuery
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.NftIdList) == 0 {
					m.NftIdList = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.NftIdList = append(m.NftIdList, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field NftIdList", wireType)
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNftCountOfRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNftCountOfRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNftCountOfRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNftCountOfResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNftCountOfResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNftCountOfResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
